name: Deploy Age Calculator to GitHub Pages

concurrency:
  group: "pages-deploy"
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Upload all files from root
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./  # deploy everything from root

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
